import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '../globals.css';
import { i18n } from '../../../i18n-config';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Esperanza Resort & SPA',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${montserrat.className} antialiased`}>{children}</body>
    </html>
  );
}
