import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Header from '@/components/shared/Header';
import { Footer } from '@/components/shared/Footer';
import '../globals.css';
import { fetchData } from '@/lib/apolloClient';
import { GLOBAL_QUERY } from '@/lib/graphql/queries';
import { GlobalQuery } from '@/gql/graphql';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Esperanza Resort & SPA',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const data = await fetchData<GlobalQuery>(GLOBAL_QUERY, { locale });

  return (
    <html lang={locale}>
      <body className={`${montserrat.className} antialiased`}>
        <Header global={data.global} />
        {children}
        <Footer global={data.global} />
      </body>
    </html>
  );
}
